### ISSUE TITLE
Image tag seems not working

### ISSUE THREAD

**Issue by alladas** [zelenin/yii2-rss#2]
Hello @zelenin ,
First of all thanks for this cool and simple to use extension.
Everything is working fine except adding images. ButI am probably missing some key details.

Could not add an **image to the channel**.
Following [The RssBoard Specifications](http://www.rssboard.org/rss-specification#ltimagegtSubelementOfLtchannelgt), here is the code I provided:
```
'channel' => [
		'title' => $appName,
		'link' => Url::toRoute('/', true),
		'description' => Yii::t('frontend', 'Upcoming events from this channel'),
		'language' => Yii::$app->language,
		'image'=> [
			'url' => $channelImg,
			'title' => $appName,
			'link' => Url::toRoute('/', true),
			'width' => 64,
			'height' => 64,
			'description' => 'LOGO',
		],
	],
```
It leads to the following error
```
call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members
```
in RssView.php line 81
Is there another way to add an image to a channel?
I have tried also to pass the image as a string without any error but the image was not rendered.

A part of that, I wanted to **add image to items** through the description tag, passing in a **CDATA with the image url + description** without no luck. Please give a look at the source screenshot.

![rsssource](https://cloud.githubusercontent.com/assets/11385698/10468097/7a3da51a-71fd-11e5-8dd3-0a998dc7d46d.png)
Many thanks for any tips or hints

**Comment by zelenin** [comment]
not-string attributes are not supported. use https://github.com/zelenin/RSS-Generator directly

**Comment by alladas** [comment]
Hi @zelenin ,
Many Thanks for your answer.
I gave a look at the RSS-Generator as you suggested.
Instead of using it directly I make the following change to "RssView" at line 81:
```
// BOF adding a fix for channel image
         if (strcmp($element,'image') === 0) {
            	$this->getFeed()->addChannelElementWithSub($element,$value);
            	continue;
         }
// EOF fix for channel image 
   $result = call_user_func($value, $this);
....
```
It is working. I did not take the risk to make it more generic with a try statement.
Now I wonder why the ending tags for channel, links, image are being shown as broken in the document source?

**Comment by zelenin** [comment]
no, it's hack. I add ```Feed``` object to callback. You may use it directly. See example from Readme.

**Comment by alladas** [comment]
Alright. Removed my change and using directly the RSS-generator.
Many thanks for your advice.
