### ISSUE TITLE
How to us Open graph tags in rss feed?

### ISSUE THREAD

**Issue by maheshtc** [zelenin/yii2-rss#3]
Is there any possibility to use open graph tags like
Description "og:description"
Locale "og:locale"
Alternate locale "og:locale:alternate"
Title "og:title"
URL "og:url"
If yes then, How can we use it?

**Comment by zelenin** [comment]
You may use ```Feed``` object in callback. See https://github.com/zelenin/yii2-rss/issues/2 and https://github.com/zelenin/RSS-Generator/blob/master/example.php#L57

**Comment by maheshtc** [comment]
Thank you for your quick response. I have another query, I tried to add open graph tag as meta tag, but after page rendering it is not shown up on rss feed page. Can give me idea  what can be the issue?

**Comment by zelenin** [comment]
Are you know what is rss-feed?
