### ISSUE TITLE
Must be an instance of Zelenin\Feed

### ISSUE THREAD

**Issue by croatiangrn** [zelenin/yii2-rss#5]
exception 'yii\base\ErrorException' with message 'Argument 2 passed to app\controllers\SiteController::app\controllers\{closure}() must be an instance of Zelenin\Feed, none given' in /home/<user>/htdocs/<project_name>/Yii/controllers/SiteController.php:202

My code
        public function actionFeed()
	    {
	    $dataProvider = new ActiveDataProvider([
	        'query' => BlogPost::find()->orderBy('id DESC')->where('published = 1'),
	        'pagination' => [
	             'pageSize' => 10
	        ],
	    ]);

	   
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        $headers = Yii::$app->response->headers;
        $headers->add('Content-Type', 'application/rss+xml');

	    echo \Zelenin\yii\extensions\Rss\RssView::widget([
	        'dataProvider' => $dataProvider,
	        'channel' => [
	            'title' => 'AIM Higher - Blog',
	            'link' => Url::toRoute(['site/feed'], true),
	            'description' => 'Posts ',
	            'language' => function ($widget, \Zelenin\Feed $feed) {
	                return Yii::$app->language;
	            },
	            'image'=> function ($widget, \Zelenin\Feed $feed) {
	                $feed->addChannelImage('http://www.dailyblogtips.com/wp-content/uploads/bigrss.gif');
	            },
	        ],
	        'items' => [
	            'title' => function ($model, $widget) {
	                    return $model->title;
	                },
	            'description' => function ($model, $widget) {
	                    return StringHelper::truncateWords($model->content, 50);
	                },
	            'link' => function ($model, $widget) {
	                    return Url::toRoute(['post/view', 'id' => $model->id], true);
	                },
	            'guid' => function ($model, $widget) {
	                    return Url::toRoute(['site/blog', 'slug' => $model->slug], true);
	                },
	            'pubDate' => function ($model, $widget) {
	            	return date('r',$model->updated_at);
	                }
	        ]
	    ]);
	}

This line 202 is on 'language'.. On localhost it works, on live server this error appears.

**Comment by zelenin** [comment]
change to ```'language' => function ($widget, $feed) {```

**Comment by croatiangrn** [comment]
Still the same error.

**Comment by zelenin** [comment]
which version?

**Comment by croatiangrn** [comment]
Yii? v2.0.6

**Comment by zelenin** [comment]
this extension

**Comment by croatiangrn** [comment]
From my composer.json

"zelenin/yii2-rss": "dev-master"

**Comment by zelenin** [comment]
try set 0.1.*

**Comment by zelenin** [comment]
$feed in callback from version 0.1.0. If you don't use $feed in callback you may remove it: ```'language' => function ($widget) {```

**Comment by croatiangrn** [comment]
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zelenin/yii2-rss 0.1.0 could not be found.

**Comment by croatiangrn** [comment]
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zelenin/yii2-rss 0.1.0 could not be found.

**Comment by zelenin** [comment]
hm, strange.

**Comment by zelenin** [comment]
my fail. i don't publish new version.
try now ~0.1

**Comment by croatiangrn** [comment]
Finally, it works. Thanks!
