### ISSUE TITLE
Passing attributes to items (like isPermalink)

### ISSUE THREAD

**Issue by beowulfenator** [zelenin/yii2-rss#6]
The README shows how an anonymous function can be used to return the `guid` field, but there is no way to set the `isPermalink` attribute. The underlying `Zelenin\Feed` class clearly supports this functionality, so it's either a feature that can be implemented in the yii2 widget, or just something that should be clarified in the docs.

**Comment by zelenin** [comment]
You can use ```Zelenin\Feed``` instance directly.
```php
            'guid' => function ($model, $widget, $feed) {
                    $feed->addItemGuid('http://example.com/post1', true);
                },
```
