### ISSUE TITLE
Class 'app\controllers\Post' not found

### ISSUE THREAD

**Issue by farhanmaba** [zelenin/yii2-rss#8]
I installed zelenin/yii2-rss through composer, and added actionRss to NewsController. But I;m getting  PHP Fatal Error – yii\base\ErrorException that Class 'app\controllers\Post' not found. code is given bellow:

`$dataProvider = new ActiveDataProvider([
        'query' => Post::find()->with(['user']),
        'pagination' => [
            'pageSize' => 10
        ],
    ]);`

Here is the screenshot:
[http://awesomescreenshot.com/04c5mg3ad7](url)

Can you help me out here please.!

**Comment by zelenin** [comment]
It's not extension issue.

**Comment by farhanmaba** [comment]
why is that so?
Post::find()->with(['user']), is part of the actionRss which you gave to add in the controller.

**Comment by zelenin** [comment]
Post is your model.
